/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ulassancak.resting

import io.ktor.client.*
import io.ktor.client.call.*
import io.ktor.client.engine.cio.*
import io.ktor.client.plugins.contentnegotiation.*
import io.ktor.client.request.*
import io.ktor.client.request.headers
import io.ktor.serialization.kotlinx.json.*
import io.ktor.client.plugins.logging.*
import kotlinx.serialization.json.Json

class RestClient {
    suspend inline fun <reified T>fetch(configuration: RequestConfiguration): T {
        val client = HttpClient(CIO) {
            install(ContentNegotiation) {
                json(Json {
                    ignoreUnknownKeys = true
                })
            }
            install(Logging)
        }
        val response = client.get(configuration.urlString) {
            url {
                configuration.headers.forEach {
                    parameters.append(it.key, it.value)
                }
            }
            headers {
                configuration.headers.forEach {
                    append(it.key, it.value)
                }
            }
        }
        val decodedObject: T = response.body();
        return decodedObject
    }
}